datasource:
  default: ${APP_ENV}
  development:
    username: ""
    password: ""
    url: jdbc:h2:./task_manager
  production:
    username: "${JDBC_DATABASE_USERNAME}"
    password: "${JDBC_DATABASE_PASSWORD}"
    url: "${JDBC_DATABASE_URL}"